services:
  app:
    restart: unless-stopped
    image: nodered/node-red:latest
    volumes:
      - ./app/data:/data
    env_file:
      - .env
    ports:
      - ${SERVE_PORT}:1880

  db:
    restart: unless-stopped
    image: postgres:14
    volumes:
      - ./app/db:/var/lib/postgresql/data
    environment:
      PGDATA: /data/postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT_EXTERNAL}:5432
